### PR TITLE
adding azure data box for .net sdk document generation

### PR DESCRIPTION
**Pull request by sojain**

### CODE REVIEW

**Comment by CamSoper** [comment]
Hi, @sojain!  Are you on the DataBox team or have a contact with them? Ideally I'd like to have a landing page included with the ref content.

**Comment by sojain** [comment]
@CamSoper , i am part of the data box team , will this serve https://azure.microsoft.com/en-us/services/storage/databox/

**Comment by CamSoper** [comment]
@sojain Sure!  What I'd like with this is a page like [this](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet) - Basically, just a one-line summary of what the package does and a really simple code sample.  In the case of the example in the link, it actually has TWO packages - One data plane and one management plane.

These are pretty quick for me to put together, so if you just want to provide me the content I can put it together for you.

**Comment by sojain** [comment]
Hope this helps
---
title: Azure .NET DataBox APIs
description: Reference for Azure Storage libraries for .NET
keywords: Azure, .NET, SDK, API, storage, blob
author: camsoper
ms.author: casoper
manager: wpickett
ms.date: 10/19/2017
ms.topic: reference
ms.devlang: dotnet
ms.service: databox
ms.custom: devcenter, svc-overview
---

# Azure DataBox APIs for .NET

## Overview

Create and manage Azure Data Box orders from your .NET applications with [Azure Data](https://docs.microsoft.com/azure/databox).

## Management APIs

Create and manage Azure Data Box orders.

Install the [NuGet package](https://www.nuget.org/packages/Microsoft.Azure.Management.DataBox) directly from the Visual Studio [Package Manager console][PackageManager] or with the [.NET Core CLI][DotNetCLI].

#### Visual Studio package manager

```powershell
Install-Package Microsoft.Azure.Management.Databox
```

#### .NET Core CLI

````bash
dotnet add package Microsoft.Azure.Management.Databox
````

### Code Example

The following example gets a databox order.

```csharp
/* Include this "using" directive...
using Microsoft.Azure.Management.Databox
*/

using (DataBoxManagementClient client = new DataBoxManagementClient(
    new TokenCloudCredentials(subscriptionId, accessToken)))
{
    JobResource job = client.Jobs.Get(resourceGroupName, jobName);
}
```

> [!div class="nextstepactions"]
> [Explore the management APIs](/dotnet/api/overview/azure/databox/management)

[PackageManager]: https://docs.microsoft.com/nuget/tools/package-manager-console
[DotNetCLI]: https://docs.microsoft.com/dotnet/core/tools/dotnet-add-package

**Pull request merged**
