### PR TITLE
update to the stream analytics page

### PR DESCRIPTION
**Pull request by MaximRouiller**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)
[api/overview/azure/stream-analytics.md](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/stream-analytics.md) | :warning:Warning | | [Details](#user-content-api%2Foverview%2Fazure%2Fstream-analytics.md)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\unbe-o-unknown\raw-\ixegie4k.rxf\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\unbe-o-unknown\raw-\ixegie4k.rxf\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name="api%2Foverview%2Fazure%2Fstream-analytics.md"></a>
### [api/overview/azure/stream-analytics.md](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/stream-analytics.md)
 - **[Warning]** Author marouill cannot be recognized in GitHub.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C19%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707191737294537-241%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MaximRouiller** [comment]
@CamSoper: What did I do? 😨

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)
[api/overview/azure/stream-analytics.md](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/stream-analytics.md) | :warning:Warning | | [Details](#user-content-api%2Foverview%2Fazure%2Fstream-analytics.md)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\rcbx-o-c33083b0\raw-\bgzoybhl.jig\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\rcbx-o-c33083b0\raw-\bgzoybhl.jig\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name="api%2Foverview%2Fazure%2Fstream-analytics.md"></a>
### [api/overview/azure/stream-analytics.md](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/stream-analytics.md)
 - **[Warning]** Author casoper cannot be recognized in GitHub.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C19%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707191747266282-241%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)
[api/overview/azure/stream-analytics.md](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/stream-analytics.md) | :warning:Warning | | [Details](#user-content-api%2Foverview%2Fazure%2Fstream-analytics.md)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\i3xe-o-d0038f03\raw-\gz1fhak1.4ey\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\i3xe-o-d0038f03\raw-\gz1fhak1.4ey\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name="api%2Foverview%2Fazure%2Fstream-analytics.md"></a>
### [api/overview/azure/stream-analytics.md](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/stream-analytics.md)
 - **[Warning]** Author casoper cannot be recognized in GitHub.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C19%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707191839282518-241%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\sutw-o-73a62a21\raw-\rneikmdg.cck\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\sutw-o-73a62a21\raw-\rneikmdg.cck\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C19%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707191935339557-241%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MaximRouiller** [comment]
@CamSoper Should I just close this PR?

**Pull request merged**
