### PR TITLE
Adding Connected Services information and adjusting TOC title

### PR DESCRIPTION
**Pull request by ghogen**

### CODE REVIEW

**Comment by ghogen** [comment]
@kraigb - this relates to https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1312241

**Comment by ghogen** [comment]
#sign-off

**Comment by ghogen** [comment]
@CamSoper I'm not sure what the process is for submitting a PR in this repo, but can you take a look at this?

**Comment by CamSoper** [comment]
@ghogen There's no process, really.  I just approve 'em and merge 'em.  Is this one ready to merge, as far as you're concerned?

**Comment by ghogen** [comment]
Yes, it's ready, please merge. :)

**Pull request merged**
