### PR TITLE
Build 581

### PR DESCRIPTION
**Pull request by v-alje**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ECMA2Yaml.Models.ECMAStore.Build()
   at ECMA2Yaml.Program.LoadAndConvert(CommandLineOptions opt)
   at ECMA2Yaml.Program.Main(String[] args)
 - **Line 231**: **[Error]** W:\gwx5-s\.optemp\packages\opbuild.scripts.1.37.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\gwx5-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\gwx5-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

<a name=""></a>
### []()
 - **[Error]** System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ECMA2Yaml.Models.ECMAStore.Build()
   at ECMA2Yaml.Program.LoadAndConvert(CommandLineOptions opt)
   at ECMA2Yaml.Program.Main(String[] args)
 - **Line 231**: **[Error]** W:\gwx5-s\.optemp\packages\opbuild.scripts.1.37.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\gwx5-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\gwx5-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C11%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201709111856136172-306%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QmvMosVi0HzU8HfLUqS0zDoKi%2F9wuTgkaexNrEcyD00%3D&st=2017-09-11T19%3A11%3A33Z&se=2017-09-12T19%3A21%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ECMA2Yaml.Models.ECMAStore.Build()
   at ECMA2Yaml.Program.LoadAndConvert(CommandLineOptions opt)
   at ECMA2Yaml.Program.Main(String[] args)
 - **Line 231**: **[Error]** W:\2dgn-s\.optemp\packages\opbuild.scripts.1.37.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\2dgn-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\2dgn-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

<a name=""></a>
### []()
 - **[Error]** System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ECMA2Yaml.Models.ECMAStore.Build()
   at ECMA2Yaml.Program.LoadAndConvert(CommandLineOptions opt)
   at ECMA2Yaml.Program.Main(String[] args)
 - **Line 231**: **[Error]** W:\2dgn-s\.optemp\packages\opbuild.scripts.1.37.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\2dgn-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\2dgn-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C11%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201709111949309716-306%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ECMA2Yaml.Models.ECMAStore.Build()
   at ECMA2Yaml.Program.LoadAndConvert(CommandLineOptions opt)
   at ECMA2Yaml.Program.Main(String[] args)
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\0bvl-log-61d17fd1\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\0bvl-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ECMA2Yaml.Models.ECMAStore.Build()
   at ECMA2Yaml.Program.LoadAndConvert(CommandLineOptions opt)
   at ECMA2Yaml.Program.Main(String[] args)
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\0bvl-log-61d17fd1\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\0bvl-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C13%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201709131545106021-306%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=g3HCMCxF4wLZbIVp60xTpZ7nSISybbFcPhOOnwKC2lY%3D&st=2017-09-13T15%3A47%3A00Z&se=2017-09-14T15%3A57%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
This is a bad PR, @v-alje, since it includes APIs that do not belong here. I am re-running the build right now to see what package is causing this. I will open a new PR with the updated content once we diagnose the root cause.

**Pull request closed without merging**
