### PR TITLE
add banners for face gate

### PR DESCRIPTION
**Pull request by PatrickFarley**
Please don't merge yet - this is for a future release

### CODE REVIEW

**Comment by jsquire** [comment]
Hi @PatrickFarley.  Just following-up to see if you're still intending to merge these changes or if we should close this PR out.

**Comment by PatrickFarley** [comment]
@jsquire Yes, still intending to merge. We don't have an ETA yet though

**Comment by PatrickFarley** [comment]
We do have an ETA now of Jun 21

**Comment by PatrickFarley** [comment]
#sign-off

**Comment by jsquire** [comment]
> @jsquire Is there anything I need to do to get this merged? I have 3 similar PRs in the other ref doc repos

Nope, just letting me know that you're ready is good enough.    Merging.

**Pull request merged**
