### PR TITLE
C60657: Adding spaces

### PR DESCRIPTION
**Pull request by v-makoud**
Hello @CamSoper, @mmacy,
Translator has reported possible source content issue. 
Description: Missing spaces break formattin on LOC pages
Please review and merge the suggested proposed file change to avoid this error. If you make related fix in another PR, then share your PR number, so we can confirm and close this PR.
Many thanks in advance.

### CODE REVIEW

**Comment by mmacy** [comment]
@v-makoud Can you provide more information about the nature of the broken formatting please? If missing whitespace at the end of a line causes rendering issues on docs, that's a bug in the tooling that needs to be reported and fixed. The trailing whitespace at end of hese lines will be removed the next time someone saves the file with "Trim trailing whitespace" enabled in their editor (a common setting to have enabled).

Cc: @dend @CamSoper

**Comment by v-makoud** [comment]
@mmacy I am checking with bugfixing team

**Comment by v-maudel** [comment]
Hi @mmacy , 
Bugfixing team confirm that :
"please inform that this is the root cause and not the tool. md guideline states that a line break is generated by a double space followed by a hard return or a double hard return, only one hard return makes the tool read this as a single line."

Regards.
Cc: @dend @CamSoper @v-makoud

**Comment by v-maudel** [comment]
Thanks @mmacy , 
Actually, that's the error. When it is parsed to other languages, hard returns that are not line breaks generated by a double space followed by a hard return (or a double hard return) are interpreted as a single line as in this image.
image
Tool read it in that way because it is the way Markdown syntax should be wrote. As far as I know this is not something that can be "fixed" in the tool.  

Also, I just want to notice that the PR wasn't merged. Maybe because this repository doesn't have automation to merge and should be done manually.

Kindly regards and thanks for your help. 
Mauricio.

**Comment by CamSoper** [comment]
I can merge it, I just wanted to make sure it wasn't waiting on something from this conversation. So we're good to merge?
________________________________

**Comment by v-maudel** [comment]
Hi @CamSoper 
@mmacy tried to sign-off after he accepted it. There is nothing on our side pending. 
If you agree and merge it will be very appreciated. 

Regards.

**Comment by mmacy** [comment]
Yup, @CamSoper, this is **GTG for merge**.

@v-makoud No worries, tool is fine as it is adhering to Markdown standards. I was more calling out where exactly the issue surfaced, not necessarily saying anything should be "fixed." :smile:

**Pull request merged**
