### PR TITLE
Update Key Vault Overview .NET

### PR DESCRIPTION
**Pull request by JeremyLikness**
Added overview description, links to helpful articles and getting started guides, examples for management and client libraries, and links to samples. @CamSoper team will review for sign-off.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/JeremyLikness/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/JeremyLikness/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\p44f-o-unknown\raw-\fg5tsavg.goc\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\p44f-o-unknown\raw-\fg5tsavg.goc\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707212107209027-253%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JeremyLikness** [comment]
@MaximRouiller do you have some reference for that? It's current in the API docs and this was taken from a recent sample that works. Here's the docs: https://msdn.microsoft.com/en-us/library/system.web.configuration.webconfigurationmanager.appsettings(v=vs.110).aspx

**Comment by MaximRouiller** [comment]
It's just a wrapper around `ConfigurationManager` anyway. The Web one needs a reference to `System.Web` and `System.Configuration` while `ConfigurationManager` just needs `System.Configuration`.

All I'm saying, this is the ASP.NET specific implementation while the generic one does the same thing and will work in other scenarios as well. 

I'm typing this from my phone so I might be wrong.

**Comment by JeremyLikness** [comment]
@MaximRouiller I think the main target being promoted for this is web apps, and this is in alignment with the sample that goes with it ... it's an easy switch but not sure it needs to change from how it's presented

**Comment by MaximRouiller** [comment]
#sign-off

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/JeremyLikness/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/JeremyLikness/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\nh20-o-24331a68\raw-\vvm1p3ku.fce\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\nh20-o-24331a68\raw-\vvm1p3ku.fce\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707241709388113-253%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
