### PR TITLE
removing broken link

### PR DESCRIPTION
**Pull request by MaximRouiller**
Fixes this issue.

https://github.com/Azure/azure-sdk-for-net/issues/25685

### CODE REVIEW

**Comment by MaximRouiller** [comment]
#sign-off

**Comment by MaximRouiller** [comment]
@CamSoper can we signoff on this?

**Review by jsquire — APPROVED** [review]

**Comment by jsquire** [comment]
@MaximRouiller:  Please let me know if you need me to merge.

**Comment by MaximRouiller** [comment]
@jsquire I don't have write access sadly, so could you please merge it?

Thanks 😃

**Pull request merged**
