### PR TITLE
changes for the Application Insights page

### PR DESCRIPTION
**Pull request by MaximRouiller**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-appinsights/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-appinsights/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\5kdu-o-unknown\raw-\i03qjl5g.nwt\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\5kdu-o-unknown\raw-\i03qjl5g.nwt\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707241926286193-263%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MaximRouiller** [comment]
@JeremyLikness If you could review this again.

The overview has been changed as per the team request. If the team wants other changes, we'll create another PR.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-appinsights/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-appinsights/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\r2zy-o-eec7f97f\raw-\xqgqgzwe.vla\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\r2zy-o-eec7f97f\raw-\xqgqgzwe.vla\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708211256579621-263%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JeremyLikness** [comment]
#sign-off

**Pull request merged**
