### PR TITLE
Update TraceTelemetry.xml

### PR DESCRIPTION
**Pull request by MS-TimothyMothra**
Update description of Timestamp, referencing @SergeyKanzhelev explanation:

https://github.com/Microsoft/ApplicationInsights-Home/issues/133
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/587

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/Microsoft.ApplicationInsights.DataContracts/TraceTelemetry.xml](https://github.com/MS-TimothyMothra/azure-docs-sdk-dotnet/blob/patch-1/xml/Microsoft.ApplicationInsights.DataContracts/TraceTelemetry.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C8%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201803082216540143-512%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wAInyZPBqzdg%2FeIlx4G4%2FcN38O4EaVbeBOEDKUSDtGo%3D&st=2018-03-08T22%3A31%3A29Z&se=2018-04-08T22%3A36%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CamSoper** [comment]
@MS-TimothyMothra - Hi there!

I'm the person who monitors these PRs.  This particular update isn't something I can merge, though, because it's a change that needs to be made to the actual C# code (rather, the `///` comments) that generated this XML file.

So here's the thing - I just learned that this was an issue (needing to modify the `///` comments rather than the XML) last week, so I'm trying to figure out a process to handle them.  I'm leaving this PR open for the moment, but I will be closing it as soon as I figure out who needs to fix the underlying code.

Thanks!

**Comment by MS-TimothyMothra** [comment]
Hello @CamSoper,
I'm the main contributor on the ApplicationInsights SDK.
I didn't realize your docs were generated! :)

I can make this same change in my repo [here](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/DataContracts/TraceTelemetry.cs).

Do I need to submit a separate request to have your *.xml files regenerated? I'm not familiar with that process. 

Thank you for your help!

**Comment by CamSoper** [comment]
You just saved me a TON of work in tracking you down, @TS-TimothyMothra!  😆 

There's a CI job that polls the public NuGet packages and generates new XML (using mdoc) when they change.  I'll merge this PR on the assumption then that you'll make the underlying change to the C# code (or Swagger? Not sure how your process works).

Also, I'm writing a talk on App Insights. Mind if I hit you up for some input?  🙂

**Comment by MS-TimothyMothra** [comment]
@CamSoper Thank you!
I've already got an open issue (linked above) for this documentation, so I won't close that until I make these changes in my repo.

Yes, feel free to ask me any questions! If I don't have the answers I can direct you to the people who do :)

**Pull request merged**
