### PR TITLE
CI job update 2018-01-30 05:02

### PR DESCRIPTION
**Pull request by botcrane**
Update from CI

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml) | :x:Error | | [Details](#user-content-api%2FMicrosoft.WindowsAzure.Storage.Blob.CloudBlob.yml)

<a name="api%2FMicrosoft.WindowsAzure.Storage.Blob.CloudBlob.yml"></a>
### [api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml)
 - **Line 1**: **[Error]** Unable to resolve [!code-csharp[DownloadToFileParallel](~/azure-storage-net/Test/Common/Blob/BlobLargeDownloadToFileTests.cs#sample_DownloadToFileParallel &quot;DownloadToFileParallel Sample&quot;)]. Can not find reference ~/azure-storage-net/Test/Common/Blob/BlobLargeDownloadToFileTests.cs.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C30%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201801300504542996-475%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Rot3oNi6dr1SGuKMaMswkZic29oCKqD2bWOPiDMgW58%3D&st=2018-01-30T05%3A14%3A58Z&se=2018-03-02T05%3A19%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
@seguler any ETA on the fix for the sample being referenced in the Storage NuGet XML?

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml) | :x:Error | | [Details](#user-content-api%2FMicrosoft.WindowsAzure.Storage.Blob.CloudBlob.yml)

<a name="api%2FMicrosoft.WindowsAzure.Storage.Blob.CloudBlob.yml"></a>
### [api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/api/Microsoft.WindowsAzure.Storage.Blob.CloudBlob.yml)
 - **Line 1**: **[Error]** Unable to resolve [!code-csharp[DownloadToFileParallel](~/azure-storage-net/Test/Common/Blob/BlobLargeDownloadToFileTests.cs#sample_DownloadToFileParallel &quot;DownloadToFileParallel Sample&quot;)]. Can not find reference ~/azure-storage-net/Test/Common/Blob/BlobLargeDownloadToFileTests.cs.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C31%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201801310502029240-475%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7uaM9EicHzfTLnxDmJOL1KPvRrbeaGmwY%2FtvjD5NuX4%3D&st=2018-01-31T05%3A10%3A11Z&se=2018-03-03T05%3A15%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/FrameworksIndex/azure-dotnet.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/FrameworksIndex/azure-dotnet.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableConstants.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableConstants.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableErrorCodeStrings.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableErrorCodeStrings.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableHttpWebRequestFactory.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableHttpWebRequestFactory.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableHttpWebResponseParsers.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableHttpWebResponseParsers.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableRequest.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table.Protocol/TableRequest.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table.Queryable/TableQueryableExtensions.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table.Queryable/TableQueryableExtensions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/CloudStorageAccountExtensions.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/CloudStorageAccountExtensions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/CloudTable.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/CloudTable.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/CloudTableClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/DynamicTableEntity.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/DynamicTableEntity.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/EdmType.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/EdmType.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/EncryptPropertyAttribute.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/EncryptPropertyAttribute.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/EntityProperty.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/EntityProperty.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/EntityPropertyConverter.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/EntityPropertyConverter.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/EntityPropertyConverterOptions.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/EntityPropertyConverterOptions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/EntityResolver`1.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/EntityResolver%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/ITableEntity.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/ITableEntity.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/IgnorePropertyAttribute.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/IgnorePropertyAttribute.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/KeyRotationEntity.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/KeyRotationEntity.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/ODataErrorHelper.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/ODataErrorHelper.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/QueryComparisons.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/QueryComparisons.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/SharedAccessTablePermissions.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/SharedAccessTablePermissions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/SharedAccessTablePolicies.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/SharedAccessTablePolicies.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/SharedAccessTablePolicy.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/SharedAccessTablePolicy.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableBatchOperation.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableBatchOperation.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableConnectionPolicy.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableConnectionPolicy.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableContinuationToken.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableContinuationToken.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableEncryptionPolicy.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableEncryptionPolicy.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableEntity.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableEntity.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableEntityAdapter`1.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableEntityAdapter%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableOperation.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableOperation.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableOperationType.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableOperationType.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableOperators.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableOperators.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TablePayloadFormat.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TablePayloadFormat.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TablePermissions.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TablePermissions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableQuery.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableQuery.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableQuerySegment`1.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableQuerySegment%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableQuery`1.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableQuery%601.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableRequestOptions.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableRequestOptions.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableResult.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableResult.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB.Table/TableResultSegment.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB.Table/TableResultSegment.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB/ConsistencyLevel.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB/ConsistencyLevel.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.Azure.CosmosDB/IndexingMode.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CosmosDB/IndexingMode.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WebBrowserNavigateErrorEventArgs.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WebBrowserNavigateErrorEventArgs.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WebBrowserNavigateErrorEventHandler.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WebBrowserNavigateErrorEventHandler.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WindowsFormsWebAuthenticationDialog.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WindowsFormsWebAuthenticationDialog.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WindowsFormsWebAuthenticationDialogBase+DpiHelper.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WindowsFormsWebAuthenticationDialogBase+DpiHelper.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WindowsFormsWebAuthenticationDialogBase.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Internal/WindowsFormsWebAuthenticationDialogBase.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Native/AsymmetricPaddingMode.xml](https://github.com/botcrane/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory.Native/AsymmetricPaddingMode.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C5%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201802050037596263-475%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Xe7Q%2B6JH98IvvPwG1ubFttUuODvmJKlB%2FMz77%2FjJISo%3D&st=2018-02-05T00%3A50%3A19Z&se=2018-03-08T00%3A55%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
