### PR TITLE
[ACI] Container Instances ref overview

### PR DESCRIPTION
**Pull request by mmacy**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[api/overview/azure/containerinstance.md](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/containerinstance?branch=pr-en-us-648) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C25%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201805251522487574-648%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=X0vH2ROcphxcW3J6Sy%2FL8djoKdDo389RvVy53JGpUZQ%3D&st=2018-05-25T17%3A07%3A24Z&se=2018-06-25T17%3A12%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[api/overview/azure/containerinstance.md](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/containerinstance?branch=pr-en-us-648) |
[docs-ref-toc/top_level_toc.yml](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C25%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201805251745370247-648%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yLjxEyhGE%2BoE1zIvm3E59ccWl4%2FDfzlp2psus%2Fhr%2FrA%3D&st=2018-05-25T18%3A40%3A25Z&se=2018-06-25T18%3A45%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[api/overview/azure/containerinstance.md](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/containerinstance?branch=pr-en-us-648) |
[docs-ref-toc/top_level_toc.yml](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-ref-overview/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C25%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201805252149431973-648%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=85Q%2B8LUCbtjcmjTtqDluwWlc2qXCH2VvwKWRESvJv6Q%3D&st=2018-05-25T22%3A45%3A29Z&se=2018-06-25T22%3A50%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mmacy** [comment]
Added a few reviewers, not sure who's on the hook for merging these...

**Comment by rloutlaw** [comment]
adding in @CamSoper  for review.

**Comment by rloutlaw** [comment]
Yes that's fine. No harm linking to GitHub.


@CamSoper please add  a work item added for the auth doc to get the CLI/PS generated file based auth steps added to the content. It'll make life way easier for new devs.

**Comment by CamSoper** [comment]
Done and done.

**Pull request merged**
