### PR TITLE
update billing overview page

### PR DESCRIPTION
**Pull request by spboyer**

### CODE REVIEW

**Comment by spboyer** [comment]
#sign-off as per @TomArcher

**Comment by spboyer** [comment]
cc:/ @CamSoper @timheuer

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/billing.md](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-1/api/overview/azure/billing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/billing?branch=pr-en-us-220) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C10%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707102042458945-220%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/billing.md](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-1/api/overview/azure/billing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/billing?branch=pr-en-us-220) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C10%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707102058098965-220%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
