### PR TITLE
Update data.tables-readme-pre.md

### PR DESCRIPTION
**Pull request by mario-guerra**
Added some text to encourage customers to use the GA version instead of this preview.

### CODE REVIEW

**Comment by mario-guerra** [comment]
#sign-off

**Review by danieljurek — APPROVED** [review]
This will be overwritten next time we release a preview version of the Azure Tables client.

**Comment by mario-guerra** [comment]
@danieljurek what file(s) do I need to modify to ensure the change is maintained through subsequent preview releases?

**Comment by danieljurek** [comment]
@mario-guerra -- We copy the content of this file from the [readme in the SDK repo](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/README.md). However, you'll have to ensure that the text is removed before you release GA otherwise the GA release page will show the content advising people to look at the GA version. 

I have an issue open to automate this -- https://github.com/Azure/azure-sdk-tools/issues/2005 ... I've put the updated copy in the issue.

**Comment by mario-guerra** [comment]
> @mario-guerra -- We copy the content of this file from the [readme in the SDK repo](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/README.md). However, you'll have to ensure that the text is removed before you release GA otherwise the GA release page will show the content advising people to look at the GA version.
> 
> I have an issue open to automate this -- [Azure/azure-sdk-tools#2005](https://github.com/Azure/azure-sdk-tools/issues/2005) ... I've put the updated copy in the issue.

Good to know, thanks Daniel.

**Pull request merged**
