### PR TITLE
Data lake toc

### PR DESCRIPTION
**Pull request by v-alje**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-toc/top_level_toc.yml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/DataLakeTOC/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201710122359598703-330%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aIEkwepY4QCjA5wt2GefVLqnO1Uwqvwi3DnjMVSCim4%3D&st=2017-10-13T00%3A15%3A31Z&se=2017-11-13T00%3A20%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
@v-alje please do not merge this. Seems like we are introducing another grouping that has not been approved by the content LT.

**Comment by dend** [comment]
@v-alje I updated the TOC to follow the proper convention.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-toc/top_level_toc.yml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/DataLakeTOC/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201710132002410521-330%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mPuEl9kE5z8hNNjYmj%2FoxI8T8U1Qv3yjYyJu6n%2FDUJw%3D&st=2017-10-13T20%3A21%3A41Z&se=2017-11-13T20%3A26%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
