### PR TITLE
Add overview text

### PR DESCRIPTION
**Pull request by spboyer**
need coding example.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\yssv-o-unknown\raw-\p2wwxk5c.dac\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\yssv-o-unknown\raw-\p2wwxk5c.dac\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707181145370042-231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\5n1c-o-68c1fb18\raw-\bz4iwjzo.i3g\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\5n1c-o-68c1fb18\raw-\bz4iwjzo.i3g\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707181151452978-231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\alil-o-c1de72ec\raw-\exg2rfpo.er5\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\alil-o-c1de72ec\raw-\exg2rfpo.er5\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707181750382027-231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-5/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\h2rs-o-c634d9be\raw-\i5bkq5r3.bh3\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\h2rs-o-c634d9be\raw-\i5bkq5r3.bh3\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707181920167677-231%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CamSoper** [comment]
Two things, @spboyer  -

1. I've asked Duncan to take a look at that stupid error.  It makes no sense.

2. Did you have an example for this one?

**Comment by spboyer** [comment]
No samples - waiting on PM for direction.

**Comment by CamSoper** [comment]
I think we can go ahead and merge it as-is then, don't you?

**Comment by spboyer** [comment]
Yes, #232  is the same situation

**Pull request merged**
