### PR TITLE
Microsoft.CognitiveServices.Speech*: remove obsolete example

### PR DESCRIPTION
**Pull request by mahilleb-msft**

### CODE REVIEW

**Comment by mahilleb-msft** [comment]
@dend - cf. our e-mail thread.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/Microsoft.CognitiveServices.Speech.Translation/TranslationRecognizer.xml](https://github.com/mahilleb-msft/azure-docs-sdk-dotnet/blob/mahilleb/fixOutOfSyncDocs/xml/Microsoft.CognitiveServices.Speech.Translation/TranslationRecognizer.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.CognitiveServices.Speech/Recognizer.xml](https://github.com/mahilleb-msft/azure-docs-sdk-dotnet/blob/mahilleb/fixOutOfSyncDocs/xml/Microsoft.CognitiveServices.Speech/Recognizer.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.CognitiveServices.Speech/SpeechRecognizer.xml](https://github.com/mahilleb-msft/azure-docs-sdk-dotnet/blob/mahilleb/fixOutOfSyncDocs/xml/Microsoft.CognitiveServices.Speech/SpeechRecognizer.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C31%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201807310528580244-734%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gjw2zpoCAYN03myVkT0752IMJKckBvSDBYxUPWnXn0U%3D&st=2018-07-31T05%3A42%3A12Z&se=2018-08-31T05%3A47%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CamSoper** [comment]
Hey @mahilleb-msft , are you on the Speech team? These fixes may need to be made in the `///` comments of the API.

**Comment by mahilleb-msft** [comment]
@camsoper - yes I am. Please contact @dend, we're following his recommendation here. With the latest CI update, example were added that came from our latest release while obsolete examples from our previous release were still kept.
I.e., the xmldoc coming from our latest release do only contain the code examples that remain after the changes in this PR.

**Comment by CamSoper** [comment]
@mahilleb-msft Oh! Okay then, I'll merge it. Thanks! :smile:

**Pull request merged**
