### PR TITLE
Adding overwrite per customer issue

### PR DESCRIPTION
**Pull request by sethmanheim**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md](https://github.com/sethmanheim/azure-docs-sdk-dotnet/blob/part-patch/docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708231702598763-294%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md](https://github.com/sethmanheim/azure-docs-sdk-dotnet/blob/part-patch/docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708231727352986-294%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md](https://github.com/sethmanheim/azure-docs-sdk-dotnet/blob/part-patch/docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.managementstrings.result?branch=pr-en-us-294) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708231745158576-294%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md](https://github.com/sethmanheim/azure-docs-sdk-dotnet/blob/part-patch/docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708231759462173-294%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md](https://github.com/sethmanheim/azure-docs-sdk-dotnet/blob/part-patch/docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708231815069251-294%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md](https://github.com/sethmanheim/azure-docs-sdk-dotnet/blob/part-patch/docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.managementstrings.namespaceentitystats?branch=pr-en-us-294) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708231822056757-294%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md](https://github.com/sethmanheim/azure-docs-sdk-dotnet/blob/part-patch/docs-ref-overwrite/ServiceBus-messaging/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.managementstrings.outgoingbytespersecond?branch=pr-en-us-294) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201708231848071912-294%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sethmanheim** [comment]
#sign-off

**Comment by mmacy** [comment]
@sethmanheim Hey Seth, should this be showing up on staging? I don't see the note on the staged article.

**Comment by sethmanheim** [comment]
@mmacy Yep I see it. It's here: https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.managementstrings.enablesubscriptionpartitioning?branch=pr-en-us-294. Are you still not seeing it?

**Comment by mmacy** [comment]
@sethmanheim Yep, that works. Merging.

**Pull request merged**
