### PR TITLE
Updated links and mentions of Cosmos DB.

### PR DESCRIPTION
**Pull request by mimig1**
Changed DocumentDB API->SQL API.

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/mimig1/azure-docs-sdk-dotnet/blob/patch-1/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-vs2015-install?branch=pr-en-us-496) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201802210341596398-496%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=L0ivlFIv7kPPR6%2Bj8D2qyNRYMSaKRwkk6UKs8lefh9s%3D&st=2018-02-21T03%3A49%3A41Z&se=2018-03-24T03%3A54%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mimig1** [comment]
@CamSoper - Do you own this TOC? If so, do you want to review my changes before sign off?

**Comment by CamSoper** [comment]
OMG, I’m so sorry I’m just now getting to this.  I’ll review today.

**Comment by CamSoper** [comment]
@mimig1 Looks fine to me!  Let me know when you'd like me to merge it.  (PRMerger isn't configured to do this repo, so @dend and I merge stuff manually).

**Comment by mimig1** [comment]
@camsoper It's ready to merge. Thanks!

**Pull request merged**
