### PR TITLE
Update samples main page

### PR DESCRIPTION
**Pull request by spboyer**
Change to create an entry page for samples similar to the [nodejs](https://docs.microsoft.com/en-us/nodejs/azure/node-samples-services-web-and-mobile?view=azure-node-2.0.0) page other than a list of how to clone repos.

### CODE REVIEW

**Comment by spboyer** [comment]
@CamSoper please review my change here as we discussed last Friday. More to come for the other pages.

**Comment by spboyer** [comment]
@CamSoper can you also remove the "Instructions" page? from the ToC?

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/dotnet-sdk-azure-web-apps-samples.md](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-8/docs-ref-conceptual/dotnet-sdk-azure-web-apps-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-web-apps-samples?branch=pr-en-us-259) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C24%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707241241591993-259%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CamSoper** [comment]
@spboyer How's your YAML?  Ideally I'd just have you include that in this PR.  The path is /docs-ref-toc/top_level_toc.yml.  If you can't/don't want to, no worries, I'll do coordinate my change with this one.

**Comment by spboyer** [comment]
@CamSoper the Instructions Page is not in the yaml page you referenced. I found it in docs-ref-conceptual/TOC.yml

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-8/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-web-apps-samples?branch=pr-en-us-259) |
[docs-ref-conceptual/dotnet-sdk-azure-web-apps-samples.md](https://github.com/spboyer/azure-docs-sdk-dotnet/blob/patch-8/docs-ref-conceptual/dotnet-sdk-azure-web-apps-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-web-apps-samples?branch=pr-en-us-259) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C25%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707251433145705-259%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spboyer** [comment]
#sign-off

**Pull request merged**
