### PR TITLE
Samples page updates

### PR DESCRIPTION
**Pull request by CamSoper**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/dotnet-samples.md](https://github.com/CamSoper/azure-docs-sdk-dotnet/blob/samples-page/docs-ref-conceptual/dotnet-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-samples?branch=pr-en-us-581) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C12%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201804122031289277-581%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VsdQ7Epb60G5V%2B1GY4%2BOX8IZnlk9Ko7Nqdl3LxvxF14%3D&st=2018-04-12T20%3A45%3A30Z&se=2018-05-13T20%3A50%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/dotnet-samples.md](https://github.com/CamSoper/azure-docs-sdk-dotnet/blob/samples-page/docs-ref-conceptual/dotnet-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-samples?branch=pr-en-us-581) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C12%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201804122106568634-581%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Jl4mcAP3JS%2F2kcJx3GqI9vKEdfAgXlrnfGCdu4ppYY0%3D&st=2018-04-12T21%3A19%3A39Z&se=2018-05-13T21%3A24%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/dotnet-samples.md](https://github.com/CamSoper/azure-docs-sdk-dotnet/blob/samples-page/docs-ref-conceptual/dotnet-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-samples?branch=pr-en-us-581) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C12%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201804122137107937-581%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Bxlpj1EximrOTx5SMVzA6p7ILI3weuFr7fOQsr9MFsY%3D&st=2018-04-12T21%3A50%3A29Z&se=2018-05-13T21%3A55%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CamSoper** [comment]
:shipit:

**Comment by CamSoper** [comment]
Looks good to me!

(Wonder how long it'll be until someone notices I've been talking to myself in this repo...)

**Pull request merged**
