### PR TITLE
changes for media services page

### PR DESCRIPTION
**Pull request by MaximRouiller**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\11tr-o-unknown\raw-\3ornlwlp.lqe\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\11tr-o-unknown\raw-\3ornlwlp.lqe\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707211204215212-250%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\03ez-o-e40314bd\raw-\3fegjln2.ts1\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\03ez-o-e40314bd\raw-\3fegjln2.ts1\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707211222013995-250%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JeremyLikness** [comment]
For @MaximRouiller: I tested dotnet add package and it doesn't appear compatible with .NET Core 1.1 so you might need to remove the dotnet add part.
No var in examples - explicit types only 
To make the example shorter you can probably start with the context line and assume token/etc. is already defined

**Comment by MaximRouiller** [comment]
@JeremyLikness should be good now.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\zxyv-o-ebfdd176\raw-\0xgtlqem.www\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\zxyv-o-ebfdd176\raw-\0xgtlqem.www\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707211328104653-250%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MaximRouiller** [comment]
@JeremyLikness done!

**Comment by JeremyLikness** [comment]
#sign-off

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\p5oj-o-80a85936\raw-\3iyyu3am.hy4\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\p5oj-o-80a85936\raw-\3iyyu3am.hy4\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707211328550806-250%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Findex.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="api%2Foverview%2Fazure%2Findex.yml"></a>
### [api/overview/azure/index.yml](https://github.com/MaximRouiller/azure-docs-sdk-dotnet/blob/aug-1-stage-mediaservices/api/overview/azure/index.yml)
 - **[Error]** Error transforming model &quot;W:\r321-o-2b2906d0\raw-\mbfrgptv.qot\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\r321-o-2b2906d0\raw-\mbfrgptv.qot\rawmodel\api\overview\azure\index.raw.json&quot; generated from &quot;api/overview/azure/index.yml&quot; using &quot;ManagedReference.html.primary.js&quot;. Error running Transform function inside template preprocessor: 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C21%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707211340289595-250%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
