### PR TITLE
Typo found on line 1016

### PR DESCRIPTION
**Pull request by nlin24**
Should "delgate" be "delegate"?

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/Microsoft.Azure.Devices.Client/DeviceClient.xml](https://github.com/nlin24/azure-docs-sdk-dotnet/blob/patch-1/xml/Microsoft.Azure.Devices.Client/DeviceClient.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C14%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201803142011485521-521%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=58wCTmIrMikEqreLpOxNo5UJklMgbPoBuMuAn2rFVtY%3D&st=2018-03-14T20%3A20%3A26Z&se=2018-04-14T20%3A25%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by CamSoper** [comment]
You are correct!  This XML is generated by `///` comments in the code, so it'll need to be fixed there or else the next release they have, it'll just overwrite your change.  I'll merge this tomorrow after I've created an issue to make a matching change in the code.

**Comment by nlin24** [comment]
Should I go ahead and close this request? Thanks.

**Comment by CamSoper** [comment]
Thank you again, @nlin24!  I've made a [corresponding PR](https://github.com/Azure/azure-iot-sdk-csharp/pull/408) to the underlying source, so I can merge your change now and feel confident it won't get overwritten by our CI process.

**Pull request merged**
