### PR TITLE
[ACI] add AUTH to API overview

### PR DESCRIPTION
**Pull request by mmacy**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/containerinstance.md](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-auth-section/api/overview/azure/containerinstance.md) | :x:Error | | [Details](#user-content-api%2Foverview%2Fazure%2Fcontainerinstance.md)

<a name="api%2Foverview%2Fazure%2Fcontainerinstance.md"></a>
### [api/overview/azure/containerinstance.md](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-auth-section/api/overview/azure/containerinstance.md)
 - **[Error]** Code absolute path: ~/aci-docs-sample-dotnet/Program.cs#azure_auth&quot;Authenticate IAzure client object&quot; is not supported in file api/overview/azure/containerinstance.md

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C11%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201806111443279571-676%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FoAtGL7H0oMu22tnz1GkYr2xh2Hoyn6R6hcfzbIRCAU%3D&st=2018-06-11T14%3A52%3A24Z&se=2018-07-12T14%3A57%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/containerinstance.md](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-auth-section/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/containerinstance?branch=pr-en-us-676) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C11%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201806111502170920-676%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UfdVlztSNIs8YZsFGibT5NYMvBRprw0Wv5ghRWMX5%2FY%3D&st=2018-06-11T15%3A12%3A42Z&se=2018-07-12T15%3A17%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mmacy** [comment]
Per comments in #648, adding the auth bits to the overview LP.

#sign-off

Cc: @CamSoper @rloutlaw

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/containerinstance.md](https://github.com/mmacy/azure-docs-sdk-dotnet/blob/aci-auth-section/api/overview/azure/containerinstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/containerinstance?branch=pr-en-us-676) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C14%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201806141442302503-676%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OCsyDTPVs6y6Ujr3fkGr9LR6QjY6TytiJYoyMAlkukU%3D&st=2018-06-14T14%3A54%3A01Z&se=2018-07-15T14%3A59%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mmacy** [comment]
#sign-off

**Comment by mmacy** [comment]
Pinging @rloutlaw @CamSoper: Not sure why **ready-to-merge** tag isn't being applied, but this one is ready to merge when you have a minute. Thanks!

**Comment by mmacy** [comment]
Hey @CamSoper, you merged this yesterday morning and it's rendering correctly on staging in master branch, but is not showing up on live site--are we needing a master-to-live branch merge, perhaps?

**Pull request merged**
