### PR TITLE
SEO Work on top dev center articles

### PR DESCRIPTION
**Pull request by kraigb**
Adding more variants for .NET, .NET Core, ASP.NET, and ASP.NET Core to hopefully affect some increase in traffic to these pages. Also added "Azure" and "web apps" in a few more places, and did some minor editing as I came across those details. 

Ignore the repeated maintainContext stuff (it was a leftover in the branch I was using, and it's identical to the changes already merged).

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/kraigb/azure-docs-sdk-dotnet/blob/kraigb-contextual-toc/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-get-started?branch=pr-en-us-720) |
[docs-ref-conceptual/dotnet-howto-migrate-app-service.md](https://github.com/kraigb/azure-docs-sdk-dotnet/blob/kraigb-contextual-toc/docs-ref-conceptual/dotnet-howto-migrate-app-service.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-howto-migrate-app-service?branch=pr-en-us-720) |
[docs-ref-conceptual/dotnet-samples.md](https://github.com/kraigb/azure-docs-sdk-dotnet/blob/kraigb-contextual-toc/docs-ref-conceptual/dotnet-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-samples?branch=pr-en-us-720) |
[docs-ref-conceptual/dotnet-sdk-azure-get-started.md](https://github.com/kraigb/azure-docs-sdk-dotnet/blob/kraigb-contextual-toc/docs-ref-conceptual/dotnet-sdk-azure-get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-get-started?branch=pr-en-us-720) |
[docs-ref-conceptual/dotnet-tools.md](https://github.com/kraigb/azure-docs-sdk-dotnet/blob/kraigb-contextual-toc/docs-ref-conceptual/dotnet-tools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-tools?branch=pr-en-us-720) |
[docs-ref-conceptual/dotnet-tutorials.md](https://github.com/kraigb/azure-docs-sdk-dotnet/blob/kraigb-contextual-toc/docs-ref-conceptual/dotnet-tutorials.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/dotnet-tutorials?branch=pr-en-us-720) |
[docs-ref-conceptual/index.yml](https://github.com/kraigb/azure-docs-sdk-dotnet/blob/kraigb-contextual-toc/docs-ref-conceptual/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/azure/index?branch=pr-en-us-720) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201807171923341370-720%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0DFubA96RC2gOWjR7RgtAaouMVfxoDfGGbRO3RC3s58%3D&st=2018-07-17T19%3A41%3A28Z&se=2018-08-17T19%3A46%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kraigb** [comment]
@CamSoper Another PR to review, this time SEO work.

**Comment by CamSoper** [comment]
@kraigb I'm actually working on a huge update for dotnet-howto-migrate-app-service.md as we speak. I'll merge this, but be aware that a complete rewrite of that doc is coming within days. Everything else is great!

**Comment by kraigb** [comment]
No problem; I'm happy to take a look when you have the revision done.

**Pull request merged**
