### PR TITLE
Event Grid overview content

### PR DESCRIPTION
**Pull request by rloutlaw**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/eventgrid.md](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/api/overview/azure/eventgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?branch=pr-en-us-616) |
[docs-ref-toc/top_level_toc.yml](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C3%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201805031639278930-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=92i4nLL85Rr45%2FPq%2FxPKVqtc2bihxUdY1xXeT3lkSD0%3D&st=2018-05-03T16%3A48%3A47Z&se=2018-06-03T16%3A53%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/eventgrid.md](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/api/overview/azure/eventgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?branch=pr-en-us-616) |
[docs-ref-toc/top_level_toc.yml](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C3%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201805031654394377-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jvq3q8n7Cr2gegwxrUuzRTOrJhpG%2B5Yctw6meLR2g5M%3D&st=2018-05-03T17%3A05%3A42Z&se=2018-06-03T17%3A10%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/eventgrid.md](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/api/overview/azure/eventgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?branch=pr-en-us-616) |
[docs-ref-toc/top_level_toc.yml](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C3%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201805031723050771-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FsCosTmpDvM%2BRdah9IcLtoj5Y5VpqBec6a%2FqTdaMMws%3D&st=2018-05-03T17%3A39%3A55Z&se=2018-06-03T17%3A44%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api/overview/azure/eventgrid.md](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/api/overview/azure/eventgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?branch=pr-en-us-616) |
[docs-ref-toc/top_level_toc.yml](https://github.com/rloutlaw/azure-docs-sdk-dotnet-1/blob/rloutlaw/event-grid-overview/docs-ref-toc/top_level_toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C3%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201805031800281464-616%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=17qiR4dxI4z9qJ8RgZ8xe8X6wRzwjPMbnQWQSFJfN5k%3D&st=2018-05-03T18%3A20%3A38Z&se=2018-06-03T18%3A25%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by rloutlaw** [comment]
@CamSoper can you review and merge this?

**Pull request merged**
