### PR TITLE
Fix greater than

### PR DESCRIPTION
**Pull request by BevLoh**
@HeidiSteen

### CODE REVIEW

**Comment by HeidiSteen** [comment]
LGTM

**Comment by BevLoh** [comment]
#sign-off

**Comment by BevLoh** [comment]
@HeidiSteen, who can approve this review?

**Comment by HeidiSteen** [comment]
@BevLoh I'm not sure because this isn't a repo I maintain or contribute to, but you could try Ted Glaza or Heath Stewart

**Comment by scbedd** [comment]
@BevLoh this documentation file is auto-generated from the nuget package. If we accept this PR it's going to get flattened on the next nightly run :(

Not only that, but the [document that this is modifying](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.synonymtokenfilter?view=azure-dotnet#properties) is actually rendering properly. 

image

The real issue is in the [track 1 docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.search.models.synonymtokenfilter?view=azure-dotnet#properties) corresponds to a [different file](https://github.com/Azure/azure-docs-sdk-dotnet/blob/21184e442057c669922b53e13a540a0afd200095/xml/Microsoft.Azure.Search.Models/SynonymTokenFilter.xml#L116).

I am tracking down possible fixes for this.

**Comment by BevLoh** [comment]
@scbedd, I had no idea. Ok, I'm going to close this PR, assuming you'll figure out a way to fix this. Let me know if you need anything from me.

**Pull request closed without merging**
