### PR TITLE
CI job update 2017-12-26 23:22

### PR DESCRIPTION
**Pull request by botcrane**
Update from CI

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Failed to load 29 files, aborting...
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\mj0t-log-00b55765\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\mj0t-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** Failed to load 29 files, aborting...
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\mj0t-log-00b55765\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\mj0t-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C26%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201712262324464996-449%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uAMsOvUZxLhhSudvGQsDr%2B7nNvGjeVevmZLkSRGxcQY%3D&st=2017-12-26T23%3A25%3A44Z&se=2018-01-26T23%3A30%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Failed to load 29 files, aborting...
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\0mqy-log-5e59a329\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\0mqy-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** Failed to load 29 files, aborting...
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\0mqy-log-5e59a329\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\0mqy-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C26%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201712262331323695-449%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yd94dhMRnUWlxX97XXRuPCslzHpg5ZiZbdpI%2F8g7MRI%3D&st=2017-12-26T23%3A32%3A33Z&se=2018-01-26T23%3A37%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
Wrong item being de-duped.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Failed to load 29 files, aborting...
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\jkjs-log-ddf1e706\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\jkjs-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** Failed to load 29 files, aborting...
 - **[Error]** System.IO.FileNotFoundException: File not found.
File name: &#39;W:\jkjs-log-ddf1e706\change-list-with-redirection.mapped.tsv&#39;
   at Microsoft.DocAsCode.Build.Engine.Incrementals.ChangeList.Parse(String tsvFile, String baseDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **Line 80**: **[Warning]** Failed to run script W:\jkjs-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C27%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201712270016582557-449%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PIy3lKWJ6WT7Jz5MypP4amPDb2xjcQnl%2FJOKt0glmD0%3D&st=2017-12-27T00%3A51%3A00Z&se=2018-01-27T00%3A56%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
