### PR TITLE
Updated global metadata for ms.topic to "reference"

### PR DESCRIPTION
**Pull request by kcpitt**

### CODE REVIEW

**Comment by kcpitt** [comment]
#sign-off

**Comment by kcpitt** [comment]
@danieljurek Is this something you can review?

**Comment by danieljurek** [comment]
@kcpitt what is the intent of this change? I don't see differences in the metadata between different pages in the review site.

**Comment by kcpitt** [comment]
@danieljurek The intent was to change the fallback ms.topic value under the Global metadata section from "conceptual" to "reference." Right now there are only 726 pages in the repo that show up with this value, but for reporting purposes, it would be better if they were aligned with the rest of the reference content. 

Ex page: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/notification-hubs-index?view=azure-dotnet 
Review site: https://review.learn.microsoft.com/en-us/dotnet/api/overview/azure/notification-hubs-index?view=azure-dotnet&branch=pr-en-us-2436

**Review by danieljurek — APPROVED** [review]
Approved. I see that this is updating some pages, just not the pages I initially looked at.

**Comment by kcpitt** [comment]
[like]  Kelly Pittman reacted to your message:
________________________________

**Pull request merged**
