### PR TITLE
Azure content update

### PR DESCRIPTION
**Pull request by dend**

### CODE REVIEW

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Failed to load 2 files, aborting...
 - **Line 210**: **[Error]** W:\zv1p-s\.optemp\packages\opbuild.scripts.1.35.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\zv1p-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\zv1p-s\_dependentPackages\splitToc\tools\run.ps1 with exit code -532462766
 - **Line 80**: **[Warning]** Failed to run script W:\zv1p-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

<a name=""></a>
### []()
 - **[Error]** Failed to load 2 files, aborting...
 - **Line 210**: **[Error]** W:\zv1p-s\.optemp\packages\opbuild.scripts.1.35.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\zv1p-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\zv1p-s\_dependentPackages\splitToc\tools\run.ps1 with exit code -532462766
 - **Line 80**: **[Warning]** Failed to run script W:\zv1p-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707181820131452-233%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Failed to load 2 files, aborting...
 - **Line 210**: **[Error]** W:\nr3w-s\.optemp\packages\opbuild.scripts.1.35.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\nr3w-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\nr3w-s\_dependentPackages\splitToc\tools\run.ps1 with exit code -532462766
 - **Line 80**: **[Warning]** Failed to run script W:\nr3w-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

<a name=""></a>
### []()
 - **[Error]** Failed to load 2 files, aborting...
 - **Line 210**: **[Error]** W:\nr3w-s\.optemp\packages\opbuild.scripts.1.35.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\nr3w-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\nr3w-s\_dependentPackages\splitToc\tools\run.ps1 with exit code -532462766
 - **Line 80**: **[Warning]** Failed to run script W:\nr3w-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707181834369527-233%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by openpublishbuild** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Failed to load 2 files, aborting...
 - **Line 210**: **[Error]** W:\bsn4-s\.optemp\packages\opbuild.scripts.1.35.4\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_postbuild in the docset azuredotnet
 - **Line 80**: **[Warning]** Failed to run script W:\bsn4-s\_dependentPackages\ECMA2Yaml\tools\Run.ps1 with exit code -1
 - **Line 80**: **[Warning]** Failed to run script W:\bsn4-s\_dependentPackages\splitToc\tools\run.ps1 with exit code -532462766
 - **Line 80**: **[Warning]** Failed to run script W:\bsn4-s\_dependentPackages\ECMA2Yaml\tools\PostBuild.ps1 with exit code 16

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C18%5C14458122-e42f-10e3-bd3d-ee1c7494cfbf%5CPullRequest%5C201707182111376810-233%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
Closing as there is an ECMA2YAML bug that is currently blocking.

**Pull request closed without merging**
