### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Broken images are not in repo. Removing broken images from line 36 and 40.

### CODE REVIEW

**Review by tfosmark — CHANGES_REQUESTED** [review]
@DhurataJ  Same as previous PR, please remove line 40 entirely. Without the image, the text string (which was there for accessibility) is not useful. Thanks!

**Review by tfosmark — APPROVED** [review]

**Comment by tfosmark** [comment]
**Global effort to fix broken links**

@Taojunshen

The Aquent team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please merge this PR. Thanks!

**Comment by jsquire** [comment]
Hi @DhurataJ.    Please be aware that this file is generated by an export process in the Azure SDK repository.   Changes here will be overwritten the next time the package is published.  The source for this content is [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/README.md); for this fix to stick across releases, we'd need to make the change there.

**Review by jsquire — APPROVED** [review]

**Review by jsquire — APPROVED** [review]

**Comment by jsquire** [comment]
Source updated by [#28114](https://github.com/Azure/azure-sdk-for-net/pull/28114).

**Pull request merged**
